name: Generate config.json with Secrets

on:
  push:
    branches: [ "main" ]

jobs:
  generate-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create config.json
      run: |-
        mkdir -p public
        echo "{\"MAP_ID\":\"${{ secrets.MAP_ID }}\", \"TOKEN_ID\":\"${{ secrets.TOKEN_ID }}\"}" > public/config.json

    - name: Commit config.json
      run: |-
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add public/config.json
        git commit -m 'Add config.json with secrets'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
